---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-partner-solutions/vse-catalog/components/apps/sriov-operator/overlays/4.10?ref=main

patches:
  - target:
      kind: SriovOperatorConfig
      name: default
    patch: |-
     - op: add
       path: '/spec/configDaemonNodeSelector'
       value: {"node-role.kubernetes.io/worker-cnf" : ""}
     - op: replace
       path: '/spec/enableInjector'
       value: true
     - op: replace
       path: '/spec/enableOperatorWebhook'
       value: true
  - target:
      kind: OperatorGroup
      namespace: openshift-sriov-network-operator
    patch: |-
     - op: replace
       path: '/metadata/name'
       value: 'sriov-network-operators'
